### ISSUE TITLE
Clarify whether orientation is in degrees or radians

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/docs#118]
This is mentioned explicitly for polar coordinates, but not mentioned for orientation.
We should work out which it is and then clarify it.

**Comment by anowlcalledjosh** [comment]
I believe the orientation values are also in degrees, based on this code which I wrote in 2017 ([source](https://github.com/systemetric/sr-2017-odroid/blob/41faff57202655ee5d712ab73bbf0f3264b95044/corrections.py#L89)):

```python
m = sqrt(d**2 + r**2 - 2 * d * r * cosd(180 - beta))
```

where `beta` is set to `marker.orientation.rot_y`.

**Comment by PeterJCLaw** [comment]
Yup, having recently looked through the `libkoki` source, I agree these are in degrees.
