### ISSUE TITLE
Restore access to Python language docs

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/docs#15]
We have historically provided access to the language docs for the version of Python which is present on the robots as a subdirectory of our docs.

The docs still link to them in places: https://studentrobotics.org/docs/python. This is no longer accessible presumably because some form of forwarding needs to be set up.

Having these docs on our website came from a direct need for the competitors to be able to look at the right docs in a canonical location -- it's remarkably hard to find the right version of the docs online.

**Comment by richardbarlow** [comment]
This appears to be fixed so I'm closing this ticket.
