### ISSUE TITLE
Changes for SR2022

### ISSUE THREAD

**Issue by raccube** [srobo/docs#218]
# Kit

- [x] #222
- [x] #223
- [x] #224
- [ ] #225
- [x] #247
- [x] #245
- [ ] Servo Board: Add note about PLOD?
- [x] WiFi: Needs removing or updating depending on whether we end up with that being shipped, regardless, there’s a reference to the forum so needs updating
- [x] #227
- [x] #241
- [ ] Functions: could add some more depth here
- [x] Libraries: update list of libraries
- [x] #282
- [x] #234
- [x] #249 
- [x] #235
- [x] #220
- [x] #221
- [x] #251
- [x] #219
- [x] Markers: remove references to libkoki
- [x] #239
- [x] #237
- [x] #226
- [x] #264
- [x] #268
- [x] #284
- [x] #231
- [x] #242
- [ ] We need a page on environments for sr.Robot3
- [x] ~Verbose Mode~ We don't think we need to document this for teams
- [ ] Debugger on robot
- [x] Diagrams and pictures can be added to vision section; see SourceBots docs for example
- [x] #257 

# Game

- [x] Update the rules
- [x] #258

**Comment by trickeydan** [comment]
Some docs that will be helpful for updating the API section: https://static.trickey.io/sr-robot3-sphinx-test/

**Comment by PeterJCLaw** [comment]
Suggest that we break the remaining tasks out to their own issues and close this one? It's not clear to me that keeping this (otherwise year-specific) issue open is helping us, especially since the year is now underway without the proposed changes here.

**Comment by trickeydan** [comment]
We have completed SR2022. Copying outstanding to new issue
