### ISSUE TITLE
New content for Programming section

### ISSUE THREAD

**Issue by raccube** [srobo/docs#225]
- [ ] Code Editors
  - [x] VS Code
  - [x] #292 
  - [ ] vscode.dev / github.dev
- [ ] Include mypy / type checking - base on SourceBots docs for PyCharm
- [ ] Recommend flake8
- [ ] VS Code Live Share
- [ ] “Collaborative Coding”
- [x] #261
- [ ] New page: Managing your code: use git, good commit message

**Comment by RealOrangeOne** [comment]
Covered as part of https://github.com/orgs/srobo/projects/25
