### ISSUE TITLE
Add instructions for flashing SD cards

### ISSUE THREAD

**Issue by raccube** [srobo/docs#257]

**Comment by trickeydan** [comment]
@RealOrangeOne Did you mention that you had some instructions for this that'd you written for SB?

**Comment by RealOrangeOne** [comment]
I did. Turns out they aren't quite as fully-fledged as I thought, but given it's a simple process, they're probably fine https://github.com/sourcebots/docs/blob/updates-and-cleanup/content/kit/pi/sd-card.md
