### ISSUE TITLE
Flashing the SD card produces an error about being unreadable

### ISSUE THREAD

**Issue by WillB97** [srobo/docs#291]
For Mac: ![image](https://user-images.githubusercontent.com/10937272/141650357-7e751b27-40d5-410a-8263-06d20f98e955.png)
But this also applies to Windows.

**Comment by raccube** [comment]
This can actually be turned in to an instruction to click Eject.

**Comment by PeterJCLaw** [comment]
Does this happen every time? If so, yeah we should mention it and tell users to eject the drive at this point.

**Comment by raccube** [comment]
Yes, it does - macOS can't read ext4.
