### ISSUE TITLE
Create hierarchical menu of pages

### ISSUE THREAD

**Issue by rgilton** [srobo/docs#3]
There needs to be a menu for the pages in the documentation.  It looks like this can be done with Jekyll's Liquid without [too much bother](https://thinkshout.com/blog/2014/12/creating-dynamic-menus-in-jekyll/).  Also with bootstrap, make it nice-looking should also be possible!

**Comment by PeterJCLaw** [comment]
I think that something like this was already done for the previous
srweb-jekyll, so it may be possible to copy from that.

**Comment by PeterJCLaw** [comment]
Looks like this got done in https://github.com/srobo/docs/commit/886069b5baa75ce9b71491d4219e4418d1e49262 and then refined somewhat in https://github.com/srobo/docs/pull/75
