### ISSUE TITLE
Interactive Troubleshooter mentions WiFi and manual control interface

### ISSUE THREAD

**Issue by raccube** [srobo/docs#311]
https://discord.com/channels/900501415548579842/908828127764050001/943126931392565249

**Comment by PeterJCLaw** [comment]
Just hit this while reviewing #350. There are a couple of places I've seen, likely best to solve this with searching the source rather than me trying to enumerate them here.

**Comment by PeterJCLaw** [comment]
It's worth noting when addressing this that the troubleshooter mentions the WiFi in the context of using the manual control interface which was previously present there.

**Comment by raccube** [comment]
Adjusted in #370 to match the new implementation
