### ISSUE TITLE
Improve servo board docs

### ISSUE THREAD

**Issue by antoinepetty** [srobo/docs#317]
Could be clearer that the index is from 0 to 11 for each servo on the board

**Comment by WillB97** [comment]
Do we even document which servo output is which? I couldn't spot it on the hardware page.

**Comment by antoinepetty** [comment]
Oops I meant this page https://studentrobotics.org/docs/programming/sr/servos/
You can work out that 0=0, especially as it's programming convention but it could probably have an explicit thing saying they're indexed 0-11

**Comment by PeterJCLaw** [comment]
Ah, yeah. Even something saying:

> The servo outputs are numbered 0-11, see the [servo board](/kit/servo_board) docs for details of which output is which.

would help.
