### ISSUE TITLE
Document that the power switch doesn't need high-gauge wire

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/docs#328]
Almost no current flows through the power switch, internal or external. The only power flowing through it is for the microcontroller so 10s of mA. Any old hookup wire will do.

**Comment by sedders123** [comment]
Do we tell them anywhere to use high-gauge?

**Comment by 8BitJosh** [comment]
Update kit assembly docs section on on/off switch to talk about either small wire or an external switch

**Comment by 8BitJosh** [comment]
#517 Note has been added to the kit assembly guide
