### ISSUE TITLE
Changes for SR2023

### ISSUE THREAD

**Issue by trickeydan** [srobo/docs#341]
# Critical 

- [x] #334
- [x] #366 
- [x] #346
- [x] #350
- [x] #344 
- [x] #368
- [x] #358

# Nice to have

- [x] Servo Board: Add note about PLOD?
- [ ] Functions: could add some more depth here
- [x] #385

# Blocked

- [ ] Terminal User Interface
- [ ] We need a page on environments for sr.robot3

**Comment by sedders123** [comment]
Calling this done for Kickstart, we can track remaining nice to haves/blocked separately if desired
