### ISSUE TITLE
API quick reference

### ISSUE THREAD

**Issue by 8BitJosh** [srobo/docs#342]
I think the api quick reference should have the following line of code added

from sr.robot3 import *

**Comment by PeterJCLaw** [comment]
Could you clarify which page you mean? (I don't think there's one called "API quick reference") Perhaps link to the page?

I initially thought you might mean https://studentrobotics.org/docs/programming/sr/, yet that does already mention `from sr.robot3 import *` within the first few paragraphs.

**Comment by WillB97** [comment]
https://studentrobotics.org/docs/programming/sr/cheat_sheet has a title of "SR API QUICK REFERENCE".

**Comment by PeterJCLaw** [comment]
Apologies I completely failed to see that.
