### ISSUE TITLE
Note how to use the auxiliary input on the servo board

### ISSUE THREAD

**Issue by WillB97** [srobo/docs#364]
In the current firmware the auxiliary power input is connected to the 5.5V regulator's output. So attaching a second power source is likely to result in damage to one of the boards.

**Comment by PeterJCLaw** [comment]
Would it be worth putting a stopper over the input, as is planned for the motor boards' spare connector?

**Comment by WillB97** [comment]
No, this is a software issue that will be fixed in the updated firmware and we have no boards that have been currently damaged by this issue.

**Comment by WillB97** [comment]
With the new firmware they need to use the auxiliary port to power ports 8-11.

**Comment by 8BitJosh** [comment]
Solved in PR #485
