### ISSUE TITLE
Add information on checking health of LiPos

### ISSUE THREAD

**Issue by trickeydan** [srobo/docs#449]
We get a lot of a queries on Discord asking whether a bloated battery is safe. We should add information and examples of batteries and checking whether they are safe. (e.g squidgy)

**Comment by 8BitJosh** [comment]
Discussion concluded that we should not provide this guidance and that we would prefer people to contact us directly if they have concerns.
We already specifiy that if a battery is swolen, has nicks/cuts in the plastic etc... that they should contact.

These issues should be delt with on a case by case basis
