### ISSUE TITLE
SR2024 - Update python libs / latest OS

### ISSUE THREAD

**Issue by 8BitJosh** [srobo/docs#496]
Update the two pages that are OS dependent with list of python libraries and the latest OS versionb

- _data/kit_versions.yml
- /kit/brain_board/python_libraries.md

**Comment by PeterJCLaw** [comment]
Note for whoever picks this up -- we'll want to update the simulator to match what the kit's using too.

**Comment by 8BitJosh** [comment]
Python versions done, awaiting kit image release

**Comment by PeterJCLaw** [comment]
> Note for whoever picks this up -- we'll want to update the simulator to match what the kit's using too.

This has happened in https://github.com/srobo/competition-simulator/pull/400
