### ISSUE TITLE
Ruby Sass gem is deprecateed

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/docs#58]
I've just run `bundle update` on this repo to pick up gem updates and saw this output:
> Post-install message from sass:
> 
> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
> 
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
>   primary implementation: https://sass-lang.com/install
> 
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
>   sassc gem: https://github.com/sass/sassc-ruby#readme
> 
> * For more details, please refer to the Sass blog:
>   http://sass.logdown.com/posts/7081811

**Comment by RealOrangeOne** [comment]
It looks like this is not a dependency we rely on directly. So we're going to have to update some dependencies of ours in the hopes they've upgraded to `sassc-ruby` already

**Comment by PeterJCLaw** [comment]
Since this is (still) the Gem in use by GitHub Pages ([3.7.4 currently](https://pages.github.com/versions/)) and we rely on GitHub Pages for rendering there's nothing we can/should do here.
