### ISSUE TITLE
Review and update docs

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/docs#60]
This replaces https://github.com/srobo/core-team-minutes/issues/12.

While we're not changing much this year, our documentation would benefit from review by fresh eyes.

In particular:
* [ ] Do we provide enough information for a complete newcomer to get started with our kit?
* [ ] Do all the links to external sites still work?
* [ ] Is what we suggest still best practice?

A very useful first part of this would be to work out some usage scenarios and raise issues for those. Each of those can then work through the docs and raise issues (or pull requests) for anything found.

**Comment by RealOrangeOne** [comment]
Now being triaged in https://github.com/orgs/srobo/projects/25
