### ISSUE TITLE
'Code a Project' menu entry

### ISSUE THREAD

**Issue by richardbarlow** [srobo/docs#87]
Is it intentional that the 'Creating a New Project' page has the sidebar menu entry title of 'Code a Project'? This doesn't seem to make sense to me.

https://github.com/srobo/docs/blob/07c30885f53751f226fe0491d707d8b8dbc22765/_data/sidebar_tree.yaml#L12

**Comment by PeterJCLaw** [comment]
I'd guess this is a typo from when the sidebar was ported over from srweb. The original commit has this text, yet srweb doesn't.
