### ISSUE TITLE
master vs. gh-pages

### ISSUE THREAD

**Issue by jimmythompson** [srobo/docs#9]
The gh-pages branch was chosen so Github Pages would work, but recently they made it so you can run gh-pages against the master branch of any repository.

I think we should merge gh-pages into master, and remove the gh-pages branch.

**Comment by richardbarlow** [comment]
Is there any reason why we cannot just flip this setting right now?

**Comment by jimmythompson** [comment]
The branches look equal to me, should be okay to switch the setting and delete the gh-pages branch.

**Comment by richardbarlow** [comment]
Done
